### ISSUE TITLE
来自Safari的抗锯齿版本

### ISSUE THREAD

**Issue by Bemly** [Fancyflame/ShadowSkin#1]
![DD69B215-63B0-47FA-A65F-511ABAB8BEF3](https://user-images.githubusercontent.com/48025099/72487381-c872f800-3848-11ea-9a9b-5ca2c7bbde8a.png)

👴🏻👴🏼👴🏽👴🏾👴🏿👴🏾👴🏽👴🏼👴🏻👴🏼👴🏽

**Comment by LovelyBemly** [comment]
![Uploading E194F0EC-DBF3-4115-9E02-CA6A65CB2442.png…]()

**Comment by Fancyflame** [comment]
🐷
